@echo off
echo Starting development server...
start cmd /c "npm run dev"
echo Starting API server...
start cmd /c "npm run api"
echo Both servers are running. Close this window to stop both servers...
pause